### PR TITLE
SlimKat (Tested)

### PR DESCRIPTION
**Pull request by ghost**
Okay sorry Ntemis for taking this over, i saw you didn't have time anymore, but i had a mate of mine push some commits to SlimKat, fixing some stuff and with Laufers changes compatibility has increased! 

Sorry for overlay removes and torch stuffs, just makes it compile, i don't even know how to fix either but yeah. 

Slimkat is A-OK so far, not lagging, volume buttons work, screen comes back on, doesn't bootloop, cam works (video Rec too after blob switch. No FC's so far, stock is a tad laggy so use iodak's. 

proof of working build.. here http://d-h.st/OtJ for testing if you don't believe me hahah! 

Have fun with SlimKat Ntemis ;) 

Sorry for new branch, seemed easier then re-doing your kk-slim. 

BIG NOTICE, YOU NEED TO CHANGE THE RECOVERY (i cba to in tree xD)  this

cd ~/slim/bootable/ && rm -rf recovery && git clone https://github.com/TeamWin/Team-Win-Recovery-Project.git recovery

Add dependencies if needed, not sure how you wanna do it, but used cm-11 branch of kernel and vendor, so keep those ;)

### CODE REVIEW

**Comment by ghost** [comment]
fuck, didn't mean to do that, how the fuck do i make it onto a new branch xD

**Comment by ghost** [comment]
Lol make a new branch of CM11 and use them commits to build with, please remember the recovery bit, make a recovery.sh in device tree that does it? sorry, still a noob at github

**Comment by ghost** [comment]
Reboot to recovery doesn't work

**Comment by laufersteppenwolf** [comment]
Closed, as slim cannot be merged into cm ;)

**Pull request closed without merging**
